version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  spark:
    build: ./spark
    container_name: spark
    environment:
      - PYSPARK_PYTHON=python3
    volumes:
      - ./spark/app:/app
    depends_on:
      - elasticsearch
    working_dir: /app
    entrypoint: ["/bin/bash"]
    tty: true
